name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
    # paths:
    #   - 'model/**'

  # to run this workflow manually from the Actions tab
  workflow_dispatch: 
  
env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  HF_USERNAME: ${{ vars.HF_USERNAME }}
  HF_REPO_NAME: model1
  
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # - name: Create and Update HF_Repo
      #   run: |
      #     bash script.sh
          
      - name: Create/Check HF_Repo
        run: |
          curl --location 'https://huggingface.co/api/repos/create' \
          --header 'Authorization: Bearer ${{ env.HF_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{
            "type": "model",
            "name": "${{ env.HF_REPO_NAME }}",
            "organization": "shellplc",
            "private":true
          }'
          
      - name: Push to HF
        run: |
          cd $HF_REPO_NAME
          git init
          git remote add origin https://$HF_USERNAME:$HF_TOKEN@huggingface.co/shellplc/$HF_REPO_NAME
          git add .
          git commit -m "contents of ${{env.HF_REPO_NAME}}"
          git push
