name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
    # paths:
    #   - 'model/**'

  # to run this workflow manually from the Actions tab
  workflow_dispatch: 
  
env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  HF_USERNAME: ${{ vars.HF_USERNAME }}
  HF_REPO_NAME: ${{ vars.HF_REPO_NAME }}
  
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # - name: list folders
        # run: |
          # bash script.sh
      # - name: list folders
      #   run: |
      #     for dir in */;
      #       do
      #         echo $dir
      #       done
          
      # - name: Create/Check HF_Repo
        #run: |
          # curl --location 'https://huggingface.co/api/repos/create' \
          # --header 'Authorization: Bearer ${{ env.HF_TOKEN }}' \
          # --header 'Content-Type: application/json' \
          # --data '{
          #   "type": "model",
          #   "name": "${{ env.HF_REPO_NAME }}",
          #   "organization": "shellplc",
          #   "private":true
          # }'
          
      # - name: Push to HF
        # run: |
          # git push --force https://$HF_USERNAME:$HF_TOKEN@huggingface.co/shellplc/$HF_REPO_NAME main 
          # git request-pull main https://$HF_USERNAME:$HF_TOKEN@huggingface.co/api/models/shellplc/$HF_REPO_NAME/preupload/main?create_pr=1 main 

      - name: Create/Update Repo
        run: |
          for dir in */;
            do
              curl --location 'https://huggingface.co/api/repos/create' \
              --header 'Authorization: Bearer ${{ env.HF_TOKEN }}' \
              --header 'Content-Type: application/json' \
              --data '{
              "type": "model",
              "name": "${{env.dir}}",
              "organization": "shellplc",
              "private":true
              }'
            git push --force https://$HF_USERNAME:$HF_TOKEN@huggingface.co/shellplc/$HF_REPO_NAME main 
            done
      
